name: GunPack
main: me.atlan1.GunPack.GunPack
version: 1.6
depend: [Spout]
load: startup
description: >
             GunPack - Create your own guns! [SPOUT]
commands:
    gunpack:
        description: Admin commands.
        aliases: gp
        usage: /gunpack reload - Reloads the config files.
permissions:
    gunpack.hud:
        description: Give permission for showing the hud.
    gunpack.reload:
        description: Give permission for the reload command.
