name: GunsPlus
main: team.GunsPlus.GunsPlus
version: 1.1
depend: [Spout]
soft-depend: [LWC, FurnaceAPI, WorldGuard, MoreMaterials]
authors: [Atlan1, SirTyler]
description: >
             Guns+ ~ Guns, Guns, Guns Galore!
commands:
    guns+:
        description: Guns+ commands.
        aliases: [g+,guns,+]
        usage: /guns+ help - Displays the Help Menu.
permissions:
    gunsplus.*:
        description: Give all permissions
        children:
            gunsplus.hud: true
            gunsplus.reload: true
    gunsplus.hud:
        description: Give permission for showing the hud.
        default: true
    gunsplus.reload:
        description: Give permission for the reload command.
        default: op
